name: Build Angular

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      working-directory: ./CaseOpener.FE
      run: npm install

    - name: Build Angular App
      working-directory: ./CaseOpener.FE
      run: npm run build -- --configuration=production
