name: Deploy Web API

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore CaseOpener.API/CaseOpener.API.sln
      
    - name: Build project
      run: dotnet build CaseOpener.API/CaseOpener.API.sln --no-restore --configuration Release

    - name: Publish project
      run: dotnet publish CaseOpener.API/CaseOpener.API/CaseOpener.API.csproj -c Release -o ${{ github.workspace }}/publish

    - name: Debug publish output
      run: ls -la ${{ github.workspace }}/publish

    - name: Compress publish directory
      run: zip -r ${{ github.workspace }}/publish.zip ${{ github.workspace }}/publish

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-app
        path: ${{ github.workspace }}/publish.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'epic-case-api'
          package: ${{ github.workspace }}/publish.zip
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_820d71e70b3d413a8eefc6751d0aa5b8 }}
