name: Build and Test .NET API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore CaseOpener.API/CaseOpener.API.sln

    - name: Build project
      run: dotnet build CaseOpener.API/CaseOpener.API.sln --no-restore

    - name: Run tests
      run: dotnet test CaseOpener.API/CaseOpener.UnitTests/CaseOpener.UnitTests.csproj --no-build --verbosity normal
